CREATE TABLE [dbo].[Users]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserName] NVARCHAR(250) NOT NULL,
	[Password] NVARCHAR(MAX) NOT NULL,
	[Mail] NVARCHAR(250)NULL,
	[Deleted] BIT DEFAULT(0),
	[DeletedDate] DATETIME NULL
)
